#!/bin/sh
#
# chkconfig: 345 99 01
# description: Kafka
#
# File : Kafka
#
# Description: Starts and stops the Kafka server
#
 
source /etc/rc.d/init.d/functions
 
KAFKA_HOME=/home/ec2-user/kafka-0.7.2-incubating-src/
KAFKA_USER=root
# See how we were called.
case "$1" in
 
  start)
    c_pid1=`ps -ef | grep zookeeper.properties | grep -v grep | awk '{print $2}'`
    if [ "$c_pid1" = "" ] ; then
     echo "Zookeeper is not running!Please start Zookeeper first using zookeeper start command"
     exit 3
    else
    echo -n "Starting Kafka:"
    /sbin/runuser $KAFKA_USER -s /bin/sh -c "$KAFKA_HOME/bin/kafka-server-start.sh $KAFKA_HOME/config/server.properties &" > /var/log/kafka.log
     echo "OK"
    exit 0
    fi
    ;;
  stop)
    echo -n "Stopping Kafka: "
    /sbin/runuser $KAFKA_USER -s /bin/sh -c "ps -ef | grep kafka.Kafka | grep -v grep | awk '{print \$2}' | xargs kill"
    echo " done."
    exit 0
    ;;
  hardstop)
    echo -n "Stopping (hard) Kafka: "
    /sbin/runuser $KAFKA_USER -s /bin/sh -c "ps -ef | grep kafka.Kafka | grep -v grep | awk '{print \$2}' | xargs kill -9"
    echo "OK"
    exit 0
    ;;
 
  status)
    c_pid=`ps -ef | grep kafka.Kafka | grep -v grep | awk '{print $2}'`
    if [ "$c_pid" = "" ] ; then
      echo "Stopped"
      exit 3
    else
      echo "Running $c_pid"
      exit 0
    fi
    ;;
 
  restart)
    echo -n "Stopping Kafka: "
    /sbin/runuser $KAFKA_USER -s /bin/sh -c "ps -ef | grep kafka.Kafka | grep -v grep | awk '{print \$2}' | xargs kill"
    echo "OK"
    echo -n "Starting Kafka:"
    /sbin/runuser $KAFKA_USER -s /bin/sh -c "$KAFKA_HOME/bin/kafka-server-start.sh $KAFKA_HOME/config/server.properties &"
    echo " done."
    exit 0
    ;;
     
  *)
    echo "Usage: kafka {start|stop|hardstop|status|restart}"
    exit 1
    ;;
 
esac
