#!/bin/sh
#
# chkconfig: 345 99 01
# description: Zookeeper
#
# File : Zookeeper	
#
# Description: Starts and stops the Zookeeper server
#

source /etc/rc.d/init.d/functions

ZOOKEEPER_HOME=/home/ec2-user/kafka-0.7.2-incubating-src/
ZOOKEEPER_USER=root
# See how we were called.
case "$1" in

  start)
    c_pid1=`ps -ef | grep zookeeper.properties | grep -v grep | awk '{print $2}'`
    if [ "$c_pid1" = "" ] ; then
      echo -n "Starting Zookeeper:"
    /sbin/runuser $ZOOKEEPER_USER -s /bin/sh -c "$ZOOKEEPER_HOME/bin/zookeeper-server-start.sh $ZOOKEEPER_HOME/config/zookeeper.properties &" > /var/log/zookeeper.log
      echo " OK " 
    else
      echo -n "Zookeeper server already running "
      echo "PID's $c_pid1"
    exit 0
    fi
    ;;

  stop)
    echo -n "Stopping Zookeeper:"
    c_pid=`ps -ef | grep zookeeper.properties | grep -v grep | awk '{print $2}'`
    /sbin/runuser $ZOOKEEPER_USER -s /bin/sh -c "ps -ef | grep zookeeper.properties | grep -v grep | awk '{print \$2}' | xargs kill -9"
    echo " OK "
    echo "Killed $c_pid"
    exit 0
    ;;
  hardstop)
    echo -n "Stopping (hard) Zookeeper: "
    /sbin/runuser $ZOOKEEPER_USER -s /bin/sh -c "ps -ef | grep zookeeper.properties | grep -v grep | awk '{print \$2}' | xargs kill -9"
    echo " OK "
    exit 0
    ;;

  status)
    c_pid=`ps -ef | grep zookeeper.properties | grep -v grep | awk '{print $2}'`
    if [ "$c_pid" = "" ] ; then
      echo "Stopped"
      exit 3
    else
      echo "Running on following PID $c_pid"
      exit 0
    fi
    ;;

  restart)
    stop
    start
    ;;

  *)
    echo "Usage: Zookeeper {start|stop|hardstop|status|restart}"
    exit 1
    ;;
 
esac

